apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: specialapplication
  name: specialapplication
spec: 
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: specialapplication
  # label keys and values that must match in order to receive traffic for this service
  selector: 
    name: specialapplication
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: specialapplication
  labels:
    name: specialapplication
spec:
  replicas: 10
  template:
    metadata:
      labels:
        name: specialapplication
    spec:
      containers:
      - name: specialapplication
        image: 172.30.168.105:5000/lab02-exercise04/specialapplication
        ports:
          - containerPort: 8080
            name: specialapplication
---
apiVersion: v1
kind: Route
metadata:
  labels:
    name: specialapplication
  name: specialapplication
spec:
  host: specialapplication.apps.example.com
  to:
    kind: Service
    name: specialapplication
status: {}
